"use client";

import { ChangeEvent, useEffect, useRef, useState } from "react";
import {
  getStartupGreeting,
  initializeSpeech,
  speak,
  stopSpeaking,
} from "../lib/speech";

import { API_BASE, analyzeVideo, spokenCue } from "../lib/api";
import type { AnalysisResponse } from "../lib/analysis";
import LiveSession from "../components/LiveSession";

const processingStages = [
  "VIDEO INGESTED",
  "PLAYER DETECTED",
  "TRACKING POSE",
  "IDENTIFYING STRIKE",
  "ANALYZING TECHNIQUE",
  "GENERATING FEEDBACK",
];

export default function Home() {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [activeStage, setActiveStage] = useState(0);
  const [result, setResult] = useState<AnalysisResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [voiceEnabled, setVoiceEnabled] = useState(true);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const hasWelcomed = useRef(false);

  useEffect(() => {
    initializeSpeech();

    return () => {
      stopSpeaking();
    };
  }, []);

  const handleFirstInteraction = () => {
    if (!voiceEnabled || hasWelcomed.current) {
      return;
    }

    hasWelcomed.current = true;
    speak(getStartupGreeting());
  };

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0] ?? null;

    setSelectedFile(file);
    setResult(null);
    setError(null);

    if (file && voiceEnabled) {
      speak("Video acquired. Ready to calibrate.");
    }
  };

  const openFilePicker = () => {
    if (!isAnalyzing) {
      fileInputRef.current?.click();
    }
  };

  const handleAnalyze = async () => {
    if (!selectedFile) return;

    setIsAnalyzing(true);
    setResult(null);
    setError(null);
    setActiveStage(0);

    if (voiceEnabled) {
      speak("Calibration complete. Beginning session analysis.");
    }

    /*
      Temporary UI progression.

      Right now FastAPI returns only when analysis is complete,
      so these stages are visual rather than real backend events.

      Later we can replace this with WebSockets / server events.
    */
    const stageTimer = window.setInterval(() => {
      setActiveStage((current) =>
        Math.min(current + 1, processingStages.length - 1)
      );
    }, 900);

    try {
      const data = await analyzeVideo(selectedFile);

      setActiveStage(processingStages.length - 1);

      // Brief pause so the final processing stage is visible.
      await new Promise((resolve) => window.setTimeout(resolve, 600));

      const analysisResult = data as AnalysisResponse;
      setResult(analysisResult);

      // Prefer the short coaching cue generated by the new report layer.
      // Fall back to the original prototype feedback if no report is available.
      const spokenFeedback = spokenCue(analysisResult);

      if (voiceEnabled && spokenFeedback) {
        speak(spokenFeedback);
      }
    } catch (err) {
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError("An unexpected error occurred.");
      }
    } finally {
      window.clearInterval(stageTimer);
      setIsAnalyzing(false);
    }
  };

  const resetAnalysis = () => {
    setSelectedFile(null);
    setResult(null);
    setError(null);
    setActiveStage(0);

    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  return (
    <main className="scan-page" onPointerDown={handleFirstInteraction}>
      {/* Background pitch */}
      <div className="pitch-background" aria-hidden="true">
        <div className="pitch-half-line" />
        <div className="pitch-center-circle" />
        <div className="pitch-center-dot" />
      </div>

      <div className="scan-line" aria-hidden="true" />

      {/* Header */}
      <header className="topbar">
        <div className="brand">
          <div className="brand-mark">S</div>

          <div>
            <div className="brand-name">SCAN</div>
            <div className="brand-subtitle">Soccer Cognitive AI Network</div>
          </div>
        </div>

        <div className="header-controls">
          <button
            className="voice-toggle"
            onClick={(event) => {
              event.stopPropagation();

              setVoiceEnabled((current) => {
                const next = !current;

                if (!next) {
                  stopSpeaking();
                }

                return next;
              });
            }}
          >
            {voiceEnabled ? "◉ VOICE ON" : "○ VOICE OFF"}
          </button>

          <div className="system-status">
            <span className="status-dot" />
            SYSTEM ONLINE
          </div>
        </div>
      </header>

      {!isAnalyzing && <LiveSession voiceEnabled={voiceEnabled} />}

      {/* PROCESSING SCREEN */}
      {isAnalyzing && (
        <section className="processing-screen">
          <div className="processing-ball">
            <div className="processing-ball-inner" />
          </div>

          <div className="processing-eyebrow">SCAN ANALYSIS ENGINE</div>

          <h2>ANALYZING SESSION</h2>

          <p>{selectedFile?.name}</p>

          <div className="processing-stages">
            {processingStages.map((stage, index) => {
              const complete = index < activeStage;
              const active = index === activeStage;

              return (
                <div
                  key={stage}
                  className={`processing-stage ${
                    complete ? "stage-complete" : ""
                  } ${active ? "stage-active" : ""}`}
                >
                  <span className="stage-indicator">
                    {complete ? "✓" : active ? "●" : "○"}
                  </span>

                  <span>{stage}</span>
                </div>
              );
            })}
          </div>

          <div className="processing-bar">
            <div
              className="processing-bar-fill"
              style={{
                width: `${
                  ((activeStage + 1) / processingStages.length) * 100
                }%`,
              }}
            />
          </div>
        </section>
      )}

      {/* RESULTS SCREEN */}
      {!isAnalyzing && result && (
        <section className="results-page">
          <div className="results-heading">
            <div>
              <div className="eyebrow">ANALYSIS COMPLETE</div>

              <h1>SESSION REPORT</h1>

              <p>Analysis ID: {result.analysis_id}</p>
            </div>

            <button className="secondary-button" onClick={resetAnalysis}>
              ANALYZE ANOTHER VIDEO
            </button>
          </div>

          <div className="results-grid">
            {/* Annotated video */}
            <div className="result-panel video-panel">
              <div className="panel-label">COMPUTER VISION OUTPUT</div>

              <video
                className="result-video"
                controls
                playsInline
                src={`${API_BASE}${result.artifacts.annotated_video}`}
              />
            </div>

            {/* Summary */}
            <div className="result-panel metrics-panel">
              <div className="panel-label">REP SUMMARY</div>

              <div className="primary-stat">
                <span>POSE COVERAGE</span>
                <strong>{Math.round(result.summary.pose_coverage * 100)}%</strong>
              </div>

              <div className="metric-list">
                <Metric
                  label="STRIKING LEG"
                  value={
                    result.summary.probable_striking_leg?.toUpperCase() ?? "—"
                  }
                />

                <Metric
                  label="STRIKE TIME"
                  value={
                    result.summary.probable_strike_time_s !== null
                      ? `${result.summary.probable_strike_time_s.toFixed(2)} s`
                      : "—"
                  }
                />

                <Metric
                  label="STRIKE FRAME"
                  value={result.summary.probable_strike_frame ?? "—"}
                />

                <Metric
                  label="TORSO LEAN"
                  value={
                    result.summary.strike_torso_lean_deg !== null
                      ? `${result.summary.strike_torso_lean_deg.toFixed(1)}°`
                      : "—"
                  }
                />

                <Metric
                  label="LEFT KNEE"
                  value={
                    result.summary.strike_left_knee_angle_deg !== null
                      ? `${result.summary.strike_left_knee_angle_deg.toFixed(1)}°`
                      : "—"
                  }
                />

                <Metric
                  label="RIGHT KNEE"
                  value={
                    result.summary.strike_right_knee_angle_deg !== null
                      ? `${result.summary.strike_right_knee_angle_deg.toFixed(1)}°`
                      : "—"
                  }
                />
              </div>
            </div>
          </div>

          {/* Feedback */}
          <div className="feedback-panel">
            <div className="feedback-header">
              <span className="feedback-icon">S</span>

              <div>
                <div className="panel-label">SCAN ANALYSIS</div>
              </div>
            </div>

            {result.coaching_report ? (
              <div className="space-y-5">
                {/* Overall Assessment */}
                <section>
                  <p className="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-emerald-400">
                    Overall Assessment
                  </p>

                  <p className="text-lg leading-8 text-zinc-100">
                    {result.coaching_report.overall_assessment}
                  </p>
                </section>

                {/* What Went Well */}
                <section className="border-t border-white/5 pt-5">
                  <p className="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-zinc-500">
                    What Went Well
                  </p>

                  <p className="text-sm leading-7 text-zinc-300">
                    {result.coaching_report.what_went_well}
                  </p>
                </section>

                {/* Primary Focus */}
                <section className="border-t border-white/5 pt-5">
                  <p className="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-zinc-500">
                    Primary Focus
                  </p>

                  <p className="text-sm leading-7 text-zinc-200">
                    {result.coaching_report.primary_focus ??
                      "No specific correction warranted"}
                  </p>
                </section>

                {/* Shot Outcome */}
                <section className="border-t border-white/5 pt-5">
                  <p className="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-zinc-500">
                    Shot Outcome
                  </p>

                  <p className="text-sm leading-7 text-zinc-300">
                    {result.coaching_report.outcome_analysis}
                  </p>
                </section>

                {/* Next Rep */}
                <section className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-5">
                  <p className="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-emerald-400">
                    Next Rep
                  </p>

                  <p className="text-sm leading-7 text-zinc-100">
                    {result.coaching_report.next_rep_recommendation}
                  </p>
                </section>

                {/* Confidence */}
                {result.coaching_report.confidence_note && (
                  <section className="border-t border-white/5 pt-5">
                    <p className="mb-3 text-xs font-semibold uppercase tracking-[0.22em] text-zinc-600">
                      SCAN Confidence
                    </p>

                    <p className="text-xs leading-6 text-zinc-500">
                      {result.coaching_report.confidence_note}
                    </p>
                  </section>
                )}
              </div>
            ) : (
              <p className="text-base leading-7 text-zinc-200">
                {result.summary.prototype_feedback}
              </p>
            )}

            <div className="prototype-warning">
              PROTOTYPE OUTPUT — TECHNICAL THRESHOLDS ARE NOT YET VALIDATED SOCCER
              BIOMECHANICS
            </div>
          </div>
        </section>
      )}

      {/* LANDING SCREEN */}
      {!isAnalyzing && !result && (
        <section className="hero">
          <div className="eyebrow">AI-POWERED TRAINING INTELLIGENCE</div>

          <h1>
            TURN EVERY REP
            <span> INTO INFORMATION.</span>
          </h1>

          <p className="hero-description">
            Upload a soccer training clip and let SCAN analyze movement,
            technique, and player state through computer vision.
          </p>

          <div
            className={`upload-panel ${
              selectedFile ? "upload-panel-selected" : ""
            }`}
            onClick={openFilePicker}
          >
            <input
              ref={fileInputRef}
              type="file"
              accept="video/mp4,video/quicktime,.mov,.mp4"
              onChange={handleFileChange}
              hidden
            />

            <div className="upload-icon">{selectedFile ? "✓" : "+"}</div>

            {selectedFile ? (
              <>
                <div className="upload-title">VIDEO READY</div>

                <div className="file-name">{selectedFile.name}</div>

                <div className="upload-hint">Click to choose a different video</div>
              </>
            ) : (
              <>
                <div className="upload-title">DROP TRAINING VIDEO</div>

                <div className="upload-hint">or click to browse</div>

                <div className="file-types">MP4 / MOV</div>
              </>
            )}
          </div>

          <button
            className="analyze-button"
            disabled={!selectedFile}
            onClick={handleAnalyze}
          >
            <span>ANALYZE SESSION</span>
            <span className="button-arrow">→</span>
          </button>

          {error && <div className="analysis-error">{error}</div>}

          <div className="pipeline-preview">
            <span>POSE TRACKING</span>
            <div className="pipeline-line" />
            <span>STRIKE DETECTION</span>
            <div className="pipeline-line" />
            <span>ADAPTIVE FEEDBACK</span>
          </div>
        </section>
      )}

      <footer className="footer">
        <span>SCAN // PROTOTYPE BUILD</span>
        <span>COMPUTER VISION · COGNITIVE AI · FOOTBALL</span>
      </footer>
    </main>
  );
}

function Metric({
  label,
  value,
}: {
  label: string;
  value: string | number;
}) {
  return (
    <div className="metric-row">
      <span>{label}</span>
      <strong>{value}</strong>
    </div>
  );
}
